{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.ingress.backend.serviceName }}
            port:
              number: {{ .Values.ingress.backend.servicePort }}
        path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.secretName }}
{{- end }}
